name: 🧠 Update GitHub Activity in README

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with GitHub activity
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "GITHUB-ACTIVITY"
          feed_list: "https://github.com/estiller28.atom"

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📄 Update recent GitHub activity [skip ci]" || echo "No changes to commit"
          git push
